plugins:
  opc:
    # mandatory properties for every plugin
    module:
      package: metzoo-python-opc-plugin
      import: from metzoo.plugins import opc

    # specific properties for the plugin (this could be anything)
    gateway: 10.211.54.175
    host_name: localhost
    server_name: Matrikon.OPC.Simulation.1

    use_opc_time: True
    time_format:  "%m/%d/%y %H:%M:%S"

    mapping:
      Random.0: {agent: "opc.random.0", metric: "random.0"}
      Random.1: {agent: "opc.random.1", metric: "random.1"}
      Random.2: {agent: "opc.random.2", metric: "random.2"}
      Random.3: {agent: "opc.random.3", metric: "random.3"}
      Random.4: {agent: "opc.random.4", metric: "random.4"}
      Random.5: {agent: "opc.random.5", metric: "random.5"}
